### ISSUE TITLE
HTTP_ROOT not defined corectly

### ISSUE THREAD

**Issue by martin131** [Ahmed-90/ts3Chan#1]
My website is located in /var/www/ts but it is symlink to /var/www/client1/web9/....
HTTP_ROOT cant be defined like that, because $_SERVER['DOCUMENT_ROOT'] you are using in str_replace return path to symlink 

example:
$_SERVER['DOCUMENT_ROOT'] = /var/www/ts.1101.cz/web
$_SERVER['HTTP_HOST'] = ts.1101.cz
HTTP_ROOT = http://ts.1101.cz/var/www/clients/client1/web9/web/request/public

It results in:
Not Found
The requested URL /var/www/clients/client1/web9/web/request/public/process/newRequest was not found on this server.

Same for ASSET_ROOT

**Comment by Ahmed-90** [comment]
Thanks for reporting the bug
the MVC part is based on https://github.com/alexgarrett/simple-mvc even tho i added the HTTP_ROOT :fearful: 

anyway i will try to fix this but am on the move (trip) atm so feel free to pull request a fix :smiley:

**Comment by IlyaBakhlin** [comment]
One question, @martin131, why did you symlink the project?

**Comment by martin131** [comment]
I use ISPconfig on my webserver and it uses symlinks for virtual servers in apache

**Comment by IlyaBakhlin** [comment]
@martin131, use the following URI:

`http://ts.1101.cz/request/public/`

I hope it helped you.

**Comment by martin131** [comment]
@IlyaBakhlin 
I already hardlinked path in source code but it is not solution for all.

**Comment by IlyaBakhlin** [comment]
@martin131, can I see the source code please?

**Comment by martin131** [comment]
@IlyaBakhlin 
Its only variable with path to real HTTP_ROOT

**Comment by IlyaBakhlin** [comment]
What?
