### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EscuderoKevin93** [Ahmed-90/ts3Chan#4]
Not Found

The requested URL /testpanekl/public/index.php was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by Ahmed-90** [comment]
Hi,

are you sure you did the right setup?? the file structure? the .htaccess file ?

**Comment by Ahmed-90** [comment]
closing this (too old no reply) feel free to reopen
