### ISSUE TITLE
Vendor autoload php?

### ISSUE THREAD

**Issue by dretax** [Ahmed-90/ts3Chan#5]
What am I doing wrong?

Warning: require_once(ts3Chanmaster/vendor/autoload.php): failed to open stream: No such file or directory in ts3Chanmaster/app/start.php on line 8

Fatal error: require_once(): Failed opening required '/ts3Chanmaster/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in ts3Chanmaster/app/start.php on line 8

**Comment by Ahmed-90** [comment]
Please follow the instructions in the readme file

you need to run composer to install dependencies

**Comment by Ahmed-90** [comment]
closing this (too old no reply) feel free to reopen
